### ISSUE TITLE
In which type of variable can be stored the output from take_image function? 

### ISSUE THREAD

**Issue by ASabovic** [zhaochenyuangit/ArduCAM-ESP32#4]
Hi,

In which type of variable the output result from take_image function can be stored?

**Comment by SelfTide** [comment]
@ASabovic the image is stored in `uint8_t *buffer` this is filled via the `void read_frame_buffer(uint8_t *buffer)` functions.

**Comment by ASabovic** [comment]
@zhaochenyuangit @SelfTide thanks a lot! I am trying to integrate your code that enables the ArduCam module with the person detection model developed for the esp32 boards. Is there a way to convert the image into grayscale? And also, have you tried the same implementation as one for the Arduino boards (with arducam and jpeg decoder libraries)?

**Comment by SelfTide** [comment]
@ASabovic this will only work with Espressif chips, since this is part of ESP-IDF.  For gray scale image, you'll have to write to the cameras registers, to do that there is a define for <a href="https://github.com/zhaochenyuangit/ArduCAM-ESP32/blob/7ab6fcd0b415fbb33724737ade64c4458fea563e/components/arducam_esp/ov2640_regs.h#L410">OV2640_YUV422</a> in this git. if you have issues you can look at <a href="https://github.com/espressif/esp32-camera/blob/2dded7c578623ebeff5b5ff468275eabf2650ea2/sensors/private_include/ov2640_settings.h#L399">esp32-camera</a> for an example of their `ov2640_settings_yuv422` settings. I have not played with grey scale yet. 

To write to the cameras registers you have to use ` wrSensorRegs8_8()` to set it accordingly. An example of this can be found <a href="https://github.com/zhaochenyuangit/ArduCAM-ESP32/blob/7ab6fcd0b415fbb33724737ade64c4458fea563e/components/arducam_esp/ArduCAM_esp_ov2640.cpp#L13">here</a> .

**Comment by zhaochenyuangit** [comment]
Same idea as @SelfTide , to obtain a greyscale image it will be better to set some control registers of the camera module so that it produces grayscale image in the first place. Conversion an RGB image to grayscale may cost a long time on MCUs.
